name: googlead
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.4.0
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.0.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
